export const uz = {
  nav: { rooms: "Xonalar", gallery: "Galereya", amenities: "Qulayliklar", location: "Joylashuv", reviews: "Sharhlar", faq: "FAQ", contact: "Aloqa", book: "Band qilish" },
  hero: { kicker: "Chilonzor tumani, Toshkent", title: "Solief Hotel", subtitle: "Toshkentda shinam mehmonxona", body: "Qulay xonalar, samimiy xizmat va oson band qilish.", rating: "4.2 / 5 Google reyting", reviews: "75 ta sharh", checkIn: "Kirish 14:00", checkOut: "Chiqish 12:00", district: "Chilonzor tumani", scroll: "Pastga" },
  actions: { request: "Band qilish so‘rovi yuborish", call: "Qo‘ng‘iroq qilish", whatsapp: "WhatsApp", telegram: "Telegram", map: "Xaritada ochish", directions: "Yo‘nalish", viewPhotos: "Barcha rasmlar", close: "Yopish", submit: "Yuborish", reset: "Tiklash", export: "JSON eksport", import: "JSON import", comingSoon: "Tez orada", previous: "Oldingi", next: "Keyingi", openPhoto: "Rasmni ochish", emailFallback: "Tayyor emailni ochish", googleProfile: "Google profili", readReviews: "Google sharhlarini o‘qish" },
  booking: { title: "Band qilish so‘rovi", checkIn: "Kirish", checkOut: "Chiqish", guests: "Mehmonlar", roomType: "Xona turi", contactMethod: "Aloqa usuli", openForm: "So‘rovni davom ettirish", noInstant: "Bu faqat so‘rov. Mehmonxona mavjudlikni tasdiqlaydi.", name: "To‘liq ism", phone: "Telefon", email: "Email", language: "Til", message: "Xabar", success: "Band qilish so‘rovingiz tayyorlandi/yuborildi. Mehmonxona jamoasi siz bilan bog‘lanadi.", chooseRoom: "Xonani tanlang", chooseContact: "Aloqa usulini tanlang", contactPhone: "Telefon", contactEmail: "Email" },
  owner: { title: "Sayt konsepti", subtitle: "Solief Hotel uchun zamonaviy to‘g‘ridan-to‘g‘ri bron tajribasi", items: ["To‘g‘ridan-to‘g‘ri so‘rov oqimi", "Uch tilli mehmon tajribasi", "Foto asosidagi taqdimot", "Admin orqali tahrir", "SEOga tayyor ko‘rinish", "Mobil bron qilish"] },
  sections: { story: "Samimiy mahalliy mehmondo‘stlik", rooms: "Amaliy va qulay xonalar", compare: "Xonalarni solishtirish", gallery: "Solief Hotel foto ko‘rinishi", amenities: "Mehmon qulayliklari", location: "Toshkent bo‘ylab qulay qatnov", reviews: "Ishonch belgilar", benefits: "Nega bevosita bog‘lanish kerak", faq: "Mehmon savollari", contact: "Solief Hotel bilan aloqa" },
  story: "Solief Hotel sodda qulaylik, samimiy xizmat va Toshkentdagi amaliy joylashuvni birlashtiradi. Ish safari, oilaviy sayohat yoki qisqa shahar tashrifi uchun mehmonxona kelishni oson va dam olishni qulay qiladi.",
  benefits: ["Mehmonxona bilan bevosita aloqa", "Tezroq javoblar", "Moslashuvchan xona so‘rovi", "Ko‘p tilli yordam", "Qo‘ng‘iroq yoki xabar", "Murakkab band qilish bosqichlarisiz"],
  room: { capacity: "Mehmon", beds: "Karavot", amenities: "Qulayliklar", priceFrom: "Boshlab", details: "Batafsil", bestFor: "Mos", breakfast: "Nonushta", wifi: "Wi-Fi", ac: "Konditsioner", bathroom: "Hammom" },
  gallery: { all: "Hammasi", exterior: "Tashqi", lobby: "Lobbi", rooms: "Xonalar", bathroom: "Hammom", kitchen: "Oshxona", dining: "Ovqatlanish", amenities: "Qulayliklar", details: "Detallar", empty: "Bu kategoriyada rasm yo‘q.", featured: "Asosiy rasm", film: "Fotolenta", story: "Foto hikoya", hint: "Rasmlarni strelkalar yoki kichik rasmlar orqali ko‘ring. Har birini to‘liq ekranda ochish mumkin." },
  location: { mapTitle: "Solief Hotel Google Maps’da", mapNote: "Joylashuv, yo‘nalish va ishonch belgilarini ko‘rsatish uchun Google Maps profili ulandi.", reviewsTitle: "Mehmonlar band qilishdan oldin nimalarni tekshiradi", reviewsSubtitle: "Bu yerda tasdiqlanmagan iqtiboslar yoki o‘ylab topilgan mehmon ismlarisiz ishonch mavzulari ko‘rsatiladi.", nearbyTitle: "Yaqin va qulay" },
  contact: { title: "So‘rov yuboring yoki qo‘ng‘iroq qiling", subtitle: "Aniq mavjudlik, xona tafsilotlari va kelish bo‘yicha yordam uchun mehmonxona bilan bog‘laning.", address: "Manzil", phone: "Telefon", email: "Email" },
  chatbot: { title: "Solief yordamchi", intro: "Mehmonxona haqida asosiy ma’lumot bilan yordam beraman.", placeholder: "Tez savol tanlang", fallback: "Asosiy ma’lumot bilan yordam beraman. Aniq mavjudlik uchun mehmonxona bilan bog‘laning.", quick: { check: "Kirish/chiqish", address: "Manzil", phone: "Telefon", rooms: "Xonalar", booking: "Band so‘rovi", map: "Xarita", amenities: "Qulayliklar" } },
  admin: { title: "Admin CRM", passcode: "Parol", login: "Kirish", intro: "Supabase asosidagi production mehmonxona CRM.", hotel: "Mehmonxona", prices: "Xona narxlari", content: "CRM ma’lumotlari", saved: "Saqlandi" },
  footer: { description: "Toshkentdagi samimiy xizmat va amaliy qulaylikka ega shinam mahalliy mehmonxona.", demo: "Sayt demo konsepti", staffPortal: "Xodimlar portali" }
};
