export const uz = {
  nav: { rooms: "Xonalar", gallery: "Galereya", amenities: "Qulayliklar", location: "Joylashuv", reviews: "Sharhlar", faq: "FAQ", contact: "Aloqa", book: "Band qilish", openMenu: "Menyuni ochish", closeMenu: "Menyuni yopish", mobileMenu: "Mobil menyu" },
  hero: { eyebrow: "Chilonzordagi butik qulaylik, Toshkent", title: "Toshkentda sokin va nafis dam olish", subtitle: "Yevropa butik nafisligi va shinam oilaviy mehmonxona iliqligi.", supporting: "Qulay xonalar, samimiy kutib olish, nonushta kiritilgan va mehmonxona jamoasidan bevosita yordam.", trustLine: "Google reyting 4.2 · 75 ta sharh · Kirish 14:00 · Chiqish 12:00", carouselLabel: "Solief Hotel rasmi", reviews: "75 ta sharh" },
  actions: { request: "Band qilish so‘rovi yuborish", call: "Qo‘ng‘iroq qilish", whatsapp: "WhatsApp", telegram: "Telegram", map: "Xaritada ochish", directions: "Yo‘nalish", viewPhotos: "Barcha rasmlar", close: "Yopish", submit: "Yuborish", reset: "Tiklash", export: "JSON eksport", import: "JSON import", comingSoon: "Tez orada", previous: "Oldingi", next: "Keyingi", openPhoto: "Rasmni ochish", emailFallback: "Tayyor emailni ochish", googleProfile: "Google profili", readReviews: "Google sharhlarini o‘qish" },
  booking: { title: "Band qilish so‘rovi", checkIn: "Kirish", checkOut: "Chiqish", guests: "Mehmonlar", roomType: "Xona turi", contactMethod: "Aloqa usuli", openForm: "So‘rovni davom ettirish", noInstant: "Bu faqat so‘rov. Mehmonxona mavjudlikni tasdiqlaydi.", name: "To‘liq ism", phone: "Telefon", email: "Email", language: "Til", message: "Xabar", success: "Band qilish so‘rovingiz yuborildi. Mehmonxona jamoasi siz bilan bog‘lanadi.", chooseRoom: "Xonani tanlang", chooseContact: "Aloqa usulini tanlang", contactPhone: "Telefon", contactEmail: "Email", checkFields: "Band qilish uchun majburiy maydonlarni to‘ldiring.", dateOrder: "Chiqish sanasi kirish sanasidan keyin bo‘lishi kerak.", requestFailed: "Band qilish so‘rovini yuborib bo‘lmadi. Iltimos, mehmonxonaga qo‘ng‘iroq qiling.", estimatedTotal: "Taxminiy jami" },
  owner: { title: "To‘g‘ridan-to‘g‘ri band qilish", subtitle: "Solief Hotelda bevosita joy band qiling", items: ["To‘g‘ridan-to‘g‘ri band qilish so‘rovlari", "Ko‘p tilli mehmon yordami", "Fotosuratli xona tafsilotlari", "Aniq xona narxlari", "Samimiy mahalliy mehmondo‘stlik", "Mobil uchun qulay band qilish"] },
  sections: { story: "Toshkent qoq markazida samimiy mehmondo‘stlik", rooms: "Qulay va oson dam olish uchun xonalar", compare: "Xonalarni solishtirish", gallery: "Solief Hotelga sokin nazar", amenities: "Har bir mehmon uchun o‘ylangan qulaylik", location: "Chilonzorda qulay joylashuv", reviews: "Toshkentga keluvchi mehmonlar ishonadi", benefits: "Nega bevosita band qilish kerak", faq: "Mehmonlarning tez-tez beradigan savollari", contact: "Solief Hotelda joyingizni band qiling" },
  story: "Solief Hotel Yevropa butik mehmonxonasining osoyishtaligi va Toshkentdagi oilaviy turar joyning iliqligini birlashtiradi. Tinch Chilonzor tumanida u ish safarlari, oilaviy tashriflar va qisqa shahar sayohatlari uchun qulay makon — nonushta kiritilgan va jamoa bevosita yordam berishga tayyor.",
  benefits: ["Mehmonxona bilan bevosita aloqa", "Tezroq javoblar", "Moslashuvchan xona so‘rovi", "Ko‘p tilli yordam", "Qo‘ng‘iroq yoki xabar", "Murakkab band qilish bosqichlarisiz"],
  room: { capacity: "Mehmon", beds: "Karavot", amenities: "Qulayliklar", priceFrom: "Boshlab", details: "Batafsil", bestFor: "Mos", breakfast: "Nonushta", wifi: "Wi-Fi", ac: "Konditsioner", bathroom: "Hammom", perNight: "bir kecha uchun", maxGuests: "Maks. mehmon", area: "Maydon", bed: "Karavot", viewDetails: "Batafsil", bookRoom: "Xonani band qilish", requestRoom: "Shu xonani so‘rash", moreAmenities: "yana qulayliklar", breakfastIncluded: "Nonushta kiritilgan", freeCancellation: "Bepul bekor qilish", noCreditCard: "Kredit karta shart emas", noSmoking: "Chekilmaydigan", petsNotAllowed: "Uy hayvonlari mumkin emas", cancellationNote: "Bekor qilish va oldindan to‘lov shartlari tarifga bog‘liq. Naqd to‘lov tarifga qarab qabul qilinishi mumkin.", conditions: "Shartlar", checkInFrom: "Kirish", checkOutUntil: "Chiqish", allAmenities: "Barcha qulayliklar", gallery: "Xona rasmlari" },
  gallery: { all: "Hammasi", exterior: "Tashqi", lobby: "Lobbi", rooms: "Xonalar", bathroom: "Hammom", kitchen: "Oshxona", dining: "Ovqatlanish", amenities: "Qulayliklar", details: "Detallar", empty: "Bu kategoriyada rasm yo‘q.", featured: "Asosiy rasm", film: "Fotolenta", story: "Foto hikoya", photos: "ta rasm", hint: "Rasmlarni strelkalar yoki kichik rasmlar orqali ko‘ring. Har birini to‘liq ekranda ochish mumkin." },
  location: { mapTitle: "Solief Hotel Google Maps’da", mapNote: "Joylashuv, yo‘nalish va ommaviy sharh belgilarini ko‘rsatish uchun Google Maps profili ulangan.", nearbyTitle: "Yaqin va qulay" },
  trust: {
    eyebrow: "Nega mehmonlar Solief’ni tanlaydi",
    subtitle: "Mehmonxona haqida aniq va halol ma’lumot — xonalar, narxlar, joylashuv va kelishdan oldin jamoa bilan bevosita aloqa.",
    ratingLabel: "Google reyting",
    verified: { title: "Tasdiqlangan Google profili", desc: "Joylashuv, yo‘nalish va ommaviy sharhlarni band qilishdan oldin Google Maps’da tekshirishingiz mumkin." },
    contact: { title: "Mehmonxona bilan bevosita aloqa", desc: "Qabulxona jamoasiga telefon yoki email orqali bog‘laning — agentliklarsiz va vositachilarsiz." },
    prices: { title: "Aniq xona narxlari", desc: "Har bir narx oldindan ko‘rsatilgan, nonushta kiritilgan va kredit karta shart emas." },
    location: { title: "Chilonzorda qulay joylashuv", desc: "Toshkent bo‘ylab qulay qatnovga ega tinch turar-joy tumani." }
  },
  contact: { title: "So‘rov yuboring yoki qo‘ng‘iroq qiling", subtitle: "Aniq mavjudlik, xona tafsilotlari va kelish bo‘yicha yordam uchun mehmonxona bilan bog‘laning.", address: "Manzil", phone: "Telefon", email: "Email" },
  chatbot: { title: "Solief yordamchi", intro: "Mehmonxona haqida asosiy ma’lumot bilan yordam beraman.", placeholder: "Tez savol tanlang", fallback: "Asosiy ma’lumot bilan yordam beraman. Aniq mavjudlik uchun mehmonxona bilan bog‘laning.", quick: { check: "Kirish/chiqish", address: "Manzil", phone: "Telefon", rooms: "Xonalar", booking: "Band so‘rovi", map: "Xarita", amenities: "Qulayliklar" } },
  admin: { title: "Admin CRM", passcode: "Parol", login: "Kirish", intro: "Supabase asosidagi production mehmonxona CRM.", hotel: "Mehmonxona", prices: "Xona narxlari", content: "CRM ma’lumotlari", saved: "Saqlandi" },
  footer: { description: "Toshkentdagi samimiy xizmat va amaliy qulaylikka ega shinam mahalliy mehmonxona.", demo: "To‘g‘ridan-to‘g‘ri band qilish", staffPortal: "Xodimlar portali", privacy: "Maxfiylik", terms: "Shartlar" }
};
