import type { Amenity } from "@/types";

export const amenities: Amenity[] = [
  { id: "wifi", icon: "Wifi", title: { en: "Free Wi-Fi", ru: "Бесплатный Wi-Fi", uz: "Bepul Wi-Fi" }, description: { en: "Easy connection for work, calls, and travel planning.", ru: "Удобная связь для работы, звонков и планов.", uz: "Ish, qo‘ng‘iroq va sayohat rejalari uchun qulay aloqa." } },
  { id: "breakfast", icon: "Coffee", title: { en: "Breakfast", ru: "Завтрак", uz: "Nonushta" }, description: { en: "A simple start to the day. Details should be confirmed by the owner.", ru: "Простое начало дня. Детали нужно подтвердить у владельца.", uz: "Kunni sodda boshlash. Tafsilotlar egasi bilan tasdiqlanadi." }, placeholder: true },
  { id: "reception", icon: "ConciergeBell", title: { en: "24/7 reception", ru: "Ресепшен 24/7", uz: "24/7 qabulxona" }, description: { en: "Guest support when arriving, leaving, or asking for help.", ru: "Помощь гостям при заезде, выезде и вопросах.", uz: "Kelish, ketish va savollar bo‘yicha yordam." } },
  { id: "ac", icon: "Snowflake", title: { en: "Air conditioning", ru: "Кондиционер", uz: "Konditsioner" }, description: { en: "Comfortable rest during warm Tashkent days.", ru: "Комфортный отдых в тёплые дни Ташкента.", uz: "Toshkentning issiq kunlarida qulay dam." } },
  { id: "bathroom", icon: "Bath", title: { en: "Private bathroom", ru: "Собственная ванная", uz: "Alohida hammom" }, description: { en: "Private, practical room comfort.", ru: "Практичный комфорт в номере.", uz: "Xonada qulay shaxsiy sharoit." } },
  { id: "family", icon: "UsersRound", title: { en: "Family rooms", ru: "Семейные номера", uz: "Oilaviy xonalar" }, description: { en: "Room options for families and small groups.", ru: "Варианты для семей и небольших групп.", uz: "Oilalar va kichik guruhlar uchun variantlar." } },
  { id: "parking", icon: "ParkingCircle", title: { en: "Parking", ru: "Парковка", uz: "Avtoturargoh" }, description: { en: "Parking availability should be confirmed when booking.", ru: "Наличие парковки лучше уточнить при бронировании.", uz: "Avtoturargohni band qilishda aniqlashtiring." }, placeholder: true },
  { id: "transfer", icon: "Plane", title: { en: "Airport transfer", ru: "Трансфер из аэропорта", uz: "Aeroport transferi" }, description: { en: "Editable service placeholder for future confirmation.", ru: "Редактируемая услуга для подтверждения.", uz: "Tasdiqlash uchun tahrirlanadigan xizmat." }, placeholder: true },
  { id: "kitchen", icon: "Utensils", title: { en: "Restaurant / kitchen", ru: "Ресторан / кухня", uz: "Restoran / oshxona" }, description: { en: "Food-service details can be updated by the hotel.", ru: "Информацию о питании можно обновить.", uz: "Ovqatlanish tafsilotlari yangilanishi mumkin." }, placeholder: true },
  { id: "laundry", icon: "Shirt", title: { en: "Laundry", ru: "Прачечная", uz: "Kir yuvish" }, description: { en: "Editable placeholder for guest convenience services.", ru: "Редактируемая услуга для удобства гостей.", uz: "Mehmonlar qulayligi uchun tahrirlanadigan xizmat." }, placeholder: true },
  { id: "nonsmoking", icon: "Ban", title: { en: "Non-smoking rooms", ru: "Номера для некурящих", uz: "Chekilmaydigan xonalar" }, description: { en: "A calmer, cleaner stay experience.", ru: "Более спокойное и чистое проживание.", uz: "Sokin va toza turar joy tajribasi." }, placeholder: true }
];
