import type { FAQ } from "@/types";
import { siteConfig } from "./siteContent";

export const faqs: FAQ[] = [
  { question: { en: "What time is check-in?", ru: "Во сколько заезд?", uz: "Kirish vaqti qachon?" }, answer: { en: `Check-in starts at ${siteConfig.checkIn}.`, ru: `Заезд начинается в ${siteConfig.checkIn}.`, uz: `Kirish ${siteConfig.checkIn} dan boshlanadi.` } },
  { question: { en: "What time is check-out?", ru: "Во сколько выезд?", uz: "Chiqish vaqti qachon?" }, answer: { en: `Check-out is until ${siteConfig.checkOut}.`, ru: `Выезд до ${siteConfig.checkOut}.`, uz: `Chiqish ${siteConfig.checkOut} gacha.` } },
  { question: { en: "How can I book a room?", ru: "Как забронировать номер?", uz: "Xonani qanday band qilaman?" }, answer: { en: "Send a booking request or call the hotel. The team will confirm availability.", ru: "Отправьте заявку или позвоните в отель. Команда подтвердит наличие мест.", uz: "Band qilish so‘rovini yuboring yoki qo‘ng‘iroq qiling. Jamoa mavjudlikni tasdiqlaydi." } },
  { question: { en: "Is breakfast available?", ru: "Есть ли завтрак?", uz: "Nonushta bormi?" }, answer: { en: "Breakfast details should be confirmed with the hotel when booking.", ru: "Детали завтрака лучше уточнить при бронировании.", uz: "Nonushta tafsilotlarini band qilishda aniqlashtiring." } },
  { question: { en: "Is Wi-Fi available?", ru: "Есть ли Wi-Fi?", uz: "Wi-Fi bormi?" }, answer: { en: "Yes, Wi-Fi is listed as a guest amenity.", ru: "Да, Wi-Fi указан как удобство для гостей.", uz: "Ha, Wi-Fi mehmonlar uchun qulaylik sifatida ko‘rsatilgan." } },
  { question: { en: "Is parking available?", ru: "Есть ли парковка?", uz: "Avtoturargoh bormi?" }, answer: { en: "Parking should be confirmed with the hotel before arrival.", ru: "Парковку лучше уточнить у отеля до приезда.", uz: "Avtoturargohni kelishdan oldin mehmonxona bilan aniqlashtiring." } },
  { question: { en: "Where is the hotel located?", ru: "Где находится отель?", uz: "Mehmonxona qayerda joylashgan?" }, answer: { en: "Solief Hotel is at Naqqoshlik 12, 100185, Tashkent, Uzbekistan, in Chilanzar district.", ru: "Solief Hotel находится по адресу Naqqoshlik 12, 100185, Ташкент, Узбекистан, Чиланзарский район.", uz: "Solief Hotel Naqqoshlik 12, 100185, Toshkent, O‘zbekiston, Chilonzor tumanida joylashgan." } },
  { question: { en: "Can I request airport transfer?", ru: "Можно заказать трансфер из аэропорта?", uz: "Aeroport transferini so‘rash mumkinmi?" }, answer: { en: "Airport transfer is a service placeholder and should be confirmed directly with the hotel.", ru: "Трансфер указан как услуга для подтверждения, уточните напрямую у отеля.", uz: "Aeroport transferi tasdiqlanishi kerak bo‘lgan xizmat, mehmonxona bilan aniqlashtiring." } },
  { question: { en: "Are family rooms available?", ru: "Есть ли семейные номера?", uz: "Oilaviy xonalar bormi?" }, answer: { en: "Family room options are available by request. Exact availability should be confirmed by the hotel.", ru: "Семейные номера доступны по запросу. Наличие нужно подтвердить у отеля.", uz: "Oilaviy xonalar so‘rov bo‘yicha mavjud. Aniq mavjudlik mehmonxona tomonidan tasdiqlanadi." } },
  { question: { en: "Can I contact the hotel by WhatsApp or Telegram?", ru: "Можно связаться через WhatsApp или Telegram?", uz: "WhatsApp yoki Telegram orqali bog‘lanish mumkinmi?" }, answer: { en: "Messaging links are configurable once the official hotel accounts are confirmed.", ru: "Ссылки на мессенджеры настраиваются после подтверждения официальных аккаунтов.", uz: "Rasmiy akkauntlar tasdiqlangach, messenjer havolalari sozlanadi." } }
];
