import type { FAQ } from "@/types";
import { siteConfig } from "./siteContent";

export const faqs: FAQ[] = [
  { question: { en: "What time is check-in?", ru: "Во сколько заезд?", uz: "Kirish vaqti qachon?" }, answer: { en: `Check-in starts at ${siteConfig.checkIn}.`, ru: `Заезд начинается в ${siteConfig.checkIn}.`, uz: `Kirish ${siteConfig.checkIn} dan boshlanadi.` } },
  { question: { en: "What time is check-out?", ru: "Во сколько выезд?", uz: "Chiqish vaqti qachon?" }, answer: { en: `Check-out is until ${siteConfig.checkOut}.`, ru: `Выезд до ${siteConfig.checkOut}.`, uz: `Chiqish ${siteConfig.checkOut} gacha.` } },
  { question: { en: "How can I book a room?", ru: "Как забронировать номер?", uz: "Xonani qanday band qilaman?" }, answer: { en: "Send a booking request or call the hotel, and the team will confirm availability directly.", ru: "Отправьте заявку или позвоните в отель — команда подтвердит наличие мест.", uz: "Band qilish so‘rovini yuboring yoki qo‘ng‘iroq qiling — jamoa mavjudlikni tasdiqlaydi." } },
  { question: { en: "Is breakfast included?", ru: "Завтрак включён?", uz: "Nonushta kiritilganmi?" }, answer: { en: "Yes — breakfast is included in every room rate.", ru: "Да, завтрак включён в стоимость каждого номера.", uz: "Ha, nonushta har bir xona narxiga kiritilgan." } },
  { question: { en: "Is Wi-Fi available?", ru: "Есть ли Wi-Fi?", uz: "Wi-Fi bormi?" }, answer: { en: "Yes, Wi-Fi is available for guests throughout the hotel.", ru: "Да, Wi-Fi доступен для гостей на всей территории отеля.", uz: "Ha, Wi-Fi mehmonlar uchun butun mehmonxona bo‘ylab mavjud." } },
  { question: { en: "Where is the hotel located?", ru: "Где находится отель?", uz: "Mehmonxona qayerda joylashgan?" }, answer: { en: "Solief Hotel is at Naqqoshlik 12, 100185, Tashkent, in Chilanzar district.", ru: "Solief Hotel находится по адресу Naqqoshlik 12, 100185, Ташкент, Чиланзарский район.", uz: "Solief Hotel Naqqoshlik 12, 100185, Toshkent, Chilonzor tumanida joylashgan." } },
  { question: { en: "Are family rooms available?", ru: "Есть ли семейные номера?", uz: "Oilaviy xonalar bormi?" }, answer: { en: "Yes — several room types suit families and small groups. Send a request and the team will help you choose.", ru: "Да — несколько типов номеров подходят для семей и небольших групп. Отправьте заявку, и команда поможет с выбором.", uz: "Ha — bir nechta xona turlari oilalar va kichik guruhlarga mos. So‘rov yuboring, jamoa tanlashga yordam beradi." } },
  { question: { en: "How can I contact the hotel?", ru: "Как связаться с отелем?", uz: "Mehmonxona bilan qanday bog‘lanish mumkin?" }, answer: { en: "You can reach the hotel directly by phone or email, and the team responds quickly to booking requests.", ru: "С отелем можно связаться напрямую по телефону или электронной почте — команда быстро отвечает на заявки.", uz: "Mehmonxona bilan telefon yoki elektron pochta orqali to‘g‘ridan-to‘g‘ri bog‘lanish mumkin — jamoa so‘rovlarga tez javob beradi." } }
];
